server:
  port: 8080

spring:
  application:
    name: product

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT:5432}/store
    username: ${DATABASE_USER:store}
    password: ${DATABASE_PASSWORD:store}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: product

  flyway:
    schemas: product
    baseline-on-migrate: true
  
store:
  jwt:
    secret-key: ${JWT_SECRET_KEY}